severity: low
exclude:
  - message: Dependencies
    paths:
      - .psci_modules
      - .spago
      - node_modules
      - output
      - packages.dhall
      - venv
      - yarn-error.log
      - yarn.lock
